[package]
name = "tac"
version = "0.1.0"
edition = "2018"
authors = ["Haruaki TAMADA"]
description = "tac implementation in Rust for practice"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
